name: Arcade Games

on:
 workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Arcade
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: nitin4568
          games: pacman,galaga,bomberman

      - name: Push generated files
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
